name: Build and Deploy

on:
  push:
    branches:
      - dev
      - los-127
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 17

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: npm i

      - name: Lint
        run: npm run lint

      - name: Get fonts
        run: |
          curl https://raw.githubusercontent.com/23-yo-designer-from-san-francisco/lostpointer-static/main/fonts.tgz --output fonts.tgz
          mkdir fonts
          cd fonts
          tar xf ../fonts.tgz

      - name: Build
        run: npm run build

      - name: Precompress static using brotli
        run: |
          brotli dist/*.{css,js,svg}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: lostpointer-static
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install rsync
        run: sudo apt install -y rsync
        
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: lostpointer-static

      - name: Upload with rsync
        run: |
          echo ${{ secrets.PRIVATE_KEY }} > /tmp/priv_key
          ssh-add /tmp/priv_key
          rsync 'ssh -i /tmp/priv_key' -avzr ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/${{ secrets.DEV_LOCATION }}
