name: Build and Deploy

on:
  push:
    branches:
      - dev
      - los-127
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 17

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: npm i

      - name: Lint
        run: npm run lint

      - name: Get fonts
        run: |
          curl https://raw.githubusercontent.com/23-yo-designer-from-san-francisco/lostpointer-static/main/fonts.tgz --output fonts.tgz
          mkdir fonts
          cd fonts
          tar xf ../fonts.tgz

      - name: Build
        run: npm run build

      - name: Precompress static using brotli
        uses: Charlesworth/compress-action@1.0.0
        with:
          target-directory: '2021_2_LostPointer_front/dist'

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: lostpointer-static
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: lostpointer-static

      - name: Rsync Deployments Action
        uses: Burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./
          remote_path: ${{ secrets.DEV_LOCATION }}
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.PRIVATE_KEY }}
